backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Imagen principal", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Autor del post", name: "author", widget: "relation", collection: "authors", searchFields: ["name", "twitterHandle"], valueField: "name", displayFields: ["twitterHandle", "followerCount"]}

  - name: "pages"
    label: "Páginas"
    files:
      - file: "src/pages/about/about.md"
        label: "Nosotros"
        name: "nosotros"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "nosotros-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/nosotros"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "authors"
    label: "Autores"
    create: true
    folder: "src/pages/authors"
    fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "author"}
          - {label: "Nombre", name: "name", widget: "string"}